spec:
  template:
    spec:
      containers:
        - livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
#          volumeMounts:
#            - name: config
#              mountPath: /app/config
#          env:
#            - name: JAVA_OPTIONS
#              value: "-Dswarm.project.stage=defaults"
#            - name: GC_MAX_METASPACE_SIZE
#              value: '200'
#      volumes:
#        - configMap:
#            name: api-gateway
#          name: config   
